// USER
export const GET_USER_SAGA = 'GET_USER_SAGA';
export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA';
export const USER_SIGNIN_SAGA = 'USER_SIGNIN_SAGA';
export const USER_SIGNUP_SAGA = 'USER_SIGNUP_SAGA';
export const USER_EDIT_SAGA = 'USER_EDIT_SAGA';
export const USER_DELETE_SAGA = 'USER_DELETE_SAGA';

// PROJECT_CATEGORY
export const GET_PROJECT_CATEGORY_SAGA = 'GET_PROJECT_CATEGORY_SAGA';

// PROJECT
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';

export const ASSIGN_USER_PROJECT_SAGA = 'ASSIGN_USER_PROJECT_SAGA';
export const REMOVE_USER_PROJECT_SAGA = 'REMOVE_USER_PROJECT_SAGA';

// TASK
export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA';
export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';
export const UPDATE_TASK_SAGA = 'UPDATE_TASK_SAGA';

export const UPDATE_TASK_DESCRIPTION_SAGA = 'UPDATE_TASK_DESCRIPTION_SAGA';
export const UPDATE_STATUS_SAGA = 'UPDATE_STATUS_SAGA';
export const UPDATE_PRIORITY_SAGA = 'UPDATE_DESCRIPTION_SAGA';
export const UPDATE_TIME_TRACKING_SAGA = 'UPDATE_TIME_TRACKING_SAGA';
export const UPDATE_ORIGINAL_ESTIMATE_SAGA = 'UPDATE_ORIGINAL_ESTIMATE_SAGA';

// TASKTYPE
export const GET_ALL_TASK_TYPE_SAGA = 'GET_ALL_TASK_TYPE_SAGA';

// PRIORITY
export const GET_ALL_PRIORITY_SAGA = 'GET_ALL_PRIORITY_SAGA';

// STATUS
export const GET_ALL_STATUS_SAGA = 'GET_ALL_STATUS_SAGA';

// COMMENT

export const GET_ALL_COMMENT_SAGA = ' GET_ALL_COMMENT_SAGA';
export const INSERT_COMMENT_SAGA = ' INSERT_COMMENT_SAGA';
export const UPDATE_COMMENT_SAGA = ' UPDATE_COMMENT_SAGA';
export const DELETE_COMMENT_SAGA = ' DELETE_COMMENT_SAGA';