// USER
export const USER_SIGNIN_SAGA = 'USER_SIGNIN_SAGA';

// PROJECT_CATEGORY
export const GET_PROJECT_CATEGORY_SAGA = 'GET_PROJECT_CATEGORY_SAGA';

// PROJECT
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';