// USER
export const USER_SIGNIN_SAGA = 'USER_SIGNIN_SAGA';
export const GET_USER_SAGA = 'GET_USER_SAGA';
export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA';

// PROJECT_CATEGORY
export const GET_PROJECT_CATEGORY_SAGA = 'GET_PROJECT_CATEGORY_SAGA';

// PROJECT
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA';
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';

export const ASSIGN_USER_PROJECT_SAGA = 'ASSIGN_USER_PROJECT_SAGA';
export const REMOVE_USER_PROJECT_SAGA = 'REMOVE_USER_PROJECT_SAGA';

// TASK
export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA';

// TASKTYPE
export const GET_ALL_TASK_TYPE_SAGA = 'GET_ALL_TASK_TYPE_SAGA';

// PRIORITY
export const GET_ALL_PRIORITY_SAGA = 'GET_ALL_PRIORITY_SAGA';

// STATUS
export const GET_ALL_STATUS_SAGA = 'GET_ALL_STATUS_SAGA';